### ISSUE TITLE
Should reducers clone initalState to guard against mutation?

### ISSUE THREAD

**Issue by lsanders** [Can-Sahin/react-boilerplate-typescript#21]
**Is your feature request related to a problem? Please describe.**
It's easy to accidentally mutate the initialState in reducers, especially from tests.

**Describe the solution you'd like**
Guard against mutation for initialState.

**Describe alternatives you've considered**
I really wouldn't want to introduce immutablejs, but maybe just lodash cloneDeep in the reducer:

```

export const initialState: ContainerState = {
  someDeepObject: new Map<string, ISomeInterface>(),
};

function myReducer(
  state: ContainerState = cloneDeep(initialState),
  action: ContainerActions): ContainerState {
  switch (action.type) {
```
Any other ideas?

**Additional context**
Thanks for the typescript fork of the awesome boilerplate!

**Comment by Can-Sahin** [comment]
Can you give an example of how you mutate the state ? Because `readonly` interfaces are simply the best solution for not mutating the state in reducers. Very simple and neat solution.

Here it doesn't let me to update fields in reducer. Is this the problem? Or something else ? 

<img width="650" alt="Screen Shot 2019-05-06 at 21 20 59" src="https://user-images.githubusercontent.com/33245689/57246043-fdd20f80-7044-11e9-8f41-bd312ddedd79.png">

**Comment by Can-Sahin** [comment]
Closing since no response and its unclear. Please open it back if you feel like
