### ISSUE TITLE
Syncing with the original upstream

### ISSUE THREAD

**Issue by Can-Sahin** [Can-Sahin/react-boilerplate-typescript#48]
@GrayStrider

There is a problem. I mentioned it at #43 

So far, I tried to keep this forks changes to very minimal. Only for synching the upstream. Because typescript changes aren't easily merging. I ve been doing it manually and lesser the changes easier it gets. 

Now that you are fixing lot of things the fork is running far apart from the original one even more which will make merging harder (its already painful) 

My idea was, keep changes minimum with extra type definitions and use exact implementation. But like in #35 you are changing the implementation too, which is good but raises my concern about merging more.

What do you suggest ?

**Comment by GrayStrider** [comment]
I will add upstream to my remotes and take a look at it.
I guess I'm fine with keeping non-TS changes minimal; but for my personal purposes I don't care about upstream that much, so I'll keep these non-TS changes at least for myself, probably by rebasing them on top of master branch. I'll look into it, perhaps it's worth adding additional branch here as well, for changes that depart from the upstream but increase the quality; even though it may lag behing the master at times due to difficulties in merging.
Also I might start submitting such PR's to upstream, so they could be merged here later. Don't like to deal with pure JS, but oh well:)

**Comment by GrayStrider** [comment]
I'll close problematic PR's for now
