### ISSUE TITLE
Reasons for omitting immer

### ISSUE THREAD

**Issue by GrayStrider** [Can-Sahin/react-boilerplate-typescript#56]
Could you please elaborate on your choice to not include immer?
I've seen you referring to TypeScript "readonly" feature as a reason, but isn't Immer also provides some performance optimizations besides immutable state?
Also, given that we're trying to match this repo with upstream as much as possible, perhaps it's worth bringing it in?

**Comment by Can-Sahin** [comment]
yeah thinking of doing it lately. But when I started there was `immutable-js` instead of `immer` and there were no types whatsoever. Spent like 2 days on it and finally decided to keep `readonly` as the solution. And stayed.. Originally the problem was immutability therefore it solved all the problem. I dont know immer much if it is performs better than clean js objects (I doubt it because react also does lot of caching and shallow comparison)

If the typescript merging is definitely green then I will implement it.
